# docker-compose.production.yml
version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: fominta/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./data/:/app/data/
  frontend:
    image: fominta/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: fominta/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/app/media
      - ./docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8080:80
